version: '3'
services:
  jees-db:
    container_name: jees-db
    image: mysql:8.0.38
    command: "--max_connections=1000 --wait_timeout=28800 --interactive_timeout=28800 --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root # ROOT用户密码
      MYSQL_DATABASE: resource # 数据库名称
      MYSQL_USER: jees # 数据库用户名
      MYSQL_PASSWORD: jees # 数据库密码
      MYSQL_ROOT_HOST: "%" # 允许远程连接
      TZ: Asia/Shanghai # 时区
    volumes:
      - /root/.jees/mysql:/var/lib/mysql
    restart: always
    networks:
      - jees-net
  jees-resource:
    container_name: jees-resource
    image: jees-resource:1.0
    ports:
      - "8000:8000"
    volumes:
      - /root/.jees:/app # 将容器内/app目录映射到宿主机/root/.jees目录
    restart: always
    networks:
      - jees-net
networks:
  jees-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24
